- name: Add Docker GPG key
  become: yes
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true

- name: Install docker-ce
  become: yes
  apt:
    update_cache: no 
    name: 
      - docker-ce
      - docker-compose
    state: present


- name: Add Ansible user to docker group
  become: yes
  user:
    name: "{{ansible_user}}"
    groups: docker

- name: Reset connection
  meta: reset_connection 

- name: Stop docker
  become: yes
  service:
    name: docker
    state: stopped
  ignore_errors: yes

- name: Enable docker
  become: yes
  service:
    name: docker
    state: started
